services:
  api-gateway:
    build: ./api-gateway
    hostname: api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - assets-service
      - payments-service
      - users-service
      - assets-transactions-service
    networks:
      - shared-network

  assets-transactions-service:
    build: assets-transactions-service
    hostname: assets-transactions-service
    ports:
      - "8084:8080"                                 # Map the container port to the host port - 8084
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb
      - assets-service
      - payments-service
      - users-service
    networks:
      - shared-network

  assets-service:
    build: assets-service
    hostname: assets-service
    container_name: assets-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql1:
        condition: service_healthy
    networks:
      - shared-network

  payments-service:
    build: payments-service
    hostname: payments-service
    container_name: payments-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres1:
        condition: service_healthy
    networks:
      - shared-network

  users-service:
    build: users-service
    hostname: users-service
    container_name: users-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql3:
        condition: service_healthy
    networks:
      - shared-network

  mysql1:
    image: mysql:5.7
    hostname: mysql1
    container_name: mysql1-assets
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=assets-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql1:/var/lib/mysql
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - shared-network

  phpmyadmin1:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin1-assets
    hostname: phpmyadmin1
    links:
      - mysql1
    restart: always
    ports:
      - "5013:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - shared-network

  postgres1:
    image: postgres:latest
    container_name: postgres1-payments
    hostname: postgres1
    environment:
      - POSTGRES_USER=user
      - PGUSER=user
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=payments-db
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -h postgres1"
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared-network

  pgadmin1:
    image: dpage/pgadmin4:latest
    container_name: pgadmin1-payments
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pallares.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "9000:80"
    depends_on:
      - postgres1
    networks:
      - shared-network

  mysql3:
    image: mysql:5.7
    hostname: mysql3
    container_name: mysql3-users
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=users-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./data/mysql3:/var/lib/mysql3
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - shared-network

  phpmyadmin3:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin3-users
    hostname: phpmyadmin3
    links:
      - mysql3
    restart: always
    ports:
      - "5015:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - shared-network

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pwd
    networks:
      - shared-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8085:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pwd
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - shared-network

volumes:
  mongo: { }

networks:
  shared-network:
    driver: bridge
