# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    pallares: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---

# Profile: h2
spring:
  config:
    activate:
      on-profile: h2

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:payments-db;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR,VALUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  sql:
    init:
      platform: h2
      mode: always

server:
  port: 7002

---

# Profile: docker
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres1:5432/payments-db
    driver-class-name: org.postgresql.Driver
    username: user
    password: pwd

    hikari:
      initializationFailTimeout: 60000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      platform: psql
      mode: always

server:
  port: 8082
