# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    pallares: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---

# for h2
spring:
  config:
    activate:
      on-profile: h2

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:assets-db;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR,VALUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  sql:
    init:
      platform: h2
      mode: always

server:
  port: 7001

---

# for docker
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://mysql1-assets:3306/assets-db
    username: user
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

    defer-datasource-initialization: true

  sql:
    init:
      platform: mysql
      mode: always

  datasource.hikari.initializationFailTimeout: 60000

server:
  port: 8081
